---
title: "Conclusions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{7. Conclusions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r label = setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, widtht = 65)
options(width = 65)
```

`mlogit` estimates a large set of random utility models with a
unified and user-friendly interface. Some of these models haven't been
presented in this article, namely:


- the rank-ordered logit model which is relevant in situations
  where individuals don't choose one among a set of mutually exclusive
  alternatives, but rank them,
- the overlapping nested logit model which is a nested logit model
  where some alternatives may belongs to more than one nest,
- the paired combinatorial logit model which is a nested logit
  model where every possible combinations of two alternatives is a
  nest,
- the multinomial probit model, obtained when the errors are
  assumed to follow a multivariate normal distribution.



All these models are illustrated in the `"mlogit"` vignette of
the `mlogit` package.

Moreover, `mlogit` provides useful functions and methods which
compute and return useful results, like predicted probabilities,
inclusive values, marginal effects, consumer surplus and individual
parameters.
