<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Kenneth Train and Yves Croissant" />

<meta name="date" content="2025-04-26" />

<title>Exercise 2: Nested logit model</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>
<script>// Hide empty <a> tag within highlighted CodeBlock for screen reader accessibility (see https://github.com/jgm/pandoc/issues/6352#issuecomment-626106786) -->
// v0.0.1
// Written by JooYoung Seo (jooyoung@psu.edu) and Atsushi Yasumoto on June 1st, 2020.

document.addEventListener('DOMContentLoaded', function() {
  const codeList = document.getElementsByClassName("sourceCode");
  for (var i = 0; i < codeList.length; i++) {
    var linkList = codeList[i].getElementsByTagName('a');
    for (var j = 0; j < linkList.length; j++) {
      if (linkList[j].innerHTML === "") {
        linkList[j].setAttribute('aria-hidden', 'true');
      }
    }
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Exercise 2: Nested logit model</h1>
<h4 class="author">Kenneth Train and Yves Croissant</h4>
<h4 class="date">2025-04-26</h4>



<p>The data set <code>HC</code> from <code>mlogit</code> contains data in <code>R</code> format on the choice of heating and central cooling system for 250 single-family, newly built houses in California.</p>
<p>The alternatives are:</p>
<ul>
<li>Gas central heat with cooling <code>gcc</code>,</li>
<li>Electric central resistence heat with cooling <code>ecc</code>,</li>
<li>Electric room resistence heat with cooling <code>erc</code>,</li>
<li>Electric heat pump, which provides cooling also <code>hpc</code>,</li>
<li>Gas central heat without cooling <code>gc</code>,</li>
<li>Electric central resistence heat without cooling <code>ec</code>,</li>
<li>Electric room resistence heat without cooling <code>er</code>.</li>
</ul>
<p>Heat pumps necessarily provide both heating and cooling such that heat pump without cooling is not an alternative.</p>
<p>The variables are:</p>
<ul>
<li><code>depvar</code> gives the name of the chosen alternative,</li>
<li><code>ich.alt</code> are the installation cost for the heating portion of the system,</li>
<li><code>icca</code> is the installation cost for cooling</li>
<li><code>och.alt</code> are the operating cost for the heating portion of the system</li>
<li><code>occa</code> is the operating cost for cooling</li>
<li><code>income</code> is the annual income of the household</li>
</ul>
<p>Note that the full installation cost of alternative <code>gcc</code> is <code>ich.gcc+icca</code>, and similarly for the operating cost and for the other alternatives with cooling.</p>
<ol class="example" style="list-style-type: decimal">
<li>Run a nested logit model on the data for two nests and one log-sum coefficient that applies to both nests. Note that the model is specified to have the cooling alternatives (<code>gcc},</code>ecc}, <code>erc},</code>hpc}) in one nest and the non-cooling alternatives (<code>gc},</code>ec}, `er}) in another nest.</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true"></a><span class="kw">library</span>(<span class="st">&quot;mlogit&quot;</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true"></a><span class="kw">data</span>(<span class="st">&quot;HC&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;mlogit&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true"></a>HC &lt;-<span class="st"> </span><span class="kw">dfidx</span>(HC, <span class="dt">varying =</span> <span class="kw">c</span>(<span class="dv">2</span><span class="op">:</span><span class="dv">8</span>, <span class="dv">10</span><span class="op">:</span><span class="dv">16</span>), <span class="dt">choice =</span> <span class="st">&quot;depvar&quot;</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true"></a>cooling.modes &lt;-<span class="st"> </span><span class="kw">idx</span>(HC, <span class="dv">2</span>) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;gcc&#39;</span>, <span class="st">&#39;ecc&#39;</span>, <span class="st">&#39;erc&#39;</span>, <span class="st">&#39;hpc&#39;</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true"></a>room.modes &lt;-<span class="st"> </span><span class="kw">idx</span>(HC, <span class="dv">2</span>) <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;erc&#39;</span>, <span class="st">&#39;er&#39;</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true"></a><span class="co"># installation / operating costs for cooling are constants, </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true"></a><span class="co"># only relevant for mixed systems</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true"></a>HC<span class="op">$</span>icca[<span class="op">!</span><span class="st"> </span>cooling.modes] &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true"></a>HC<span class="op">$</span>occa[<span class="op">!</span><span class="st"> </span>cooling.modes] &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true"></a><span class="co"># create income variables for two sets cooling and rooms</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true"></a>HC<span class="op">$</span>inc.cooling &lt;-<span class="st"> </span>HC<span class="op">$</span>inc.room &lt;-<span class="st"> </span><span class="dv">0</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true"></a>HC<span class="op">$</span>inc.cooling[cooling.modes] &lt;-<span class="st"> </span>HC<span class="op">$</span>income[cooling.modes]</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true"></a>HC<span class="op">$</span>inc.room[room.modes] &lt;-<span class="st"> </span>HC<span class="op">$</span>income[room.modes]</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true"></a><span class="co"># create an intercet for cooling modes</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true"></a>HC<span class="op">$</span>int.cooling &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(cooling.modes)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true"></a><span class="co"># estimate the model with only one nest elasticity</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true"></a>nl &lt;-<span class="st"> </span><span class="kw">mlogit</span>(depvar <span class="op">~</span><span class="st"> </span>ich <span class="op">+</span><span class="st"> </span>och <span class="op">+</span>icca <span class="op">+</span><span class="st"> </span>occa <span class="op">+</span><span class="st"> </span>inc.room <span class="op">+</span><span class="st"> </span>inc.cooling <span class="op">+</span><span class="st"> </span>int.cooling <span class="op">|</span><span class="st"> </span><span class="dv">0</span>, HC,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true"></a>             <span class="dt">nests =</span> <span class="kw">list</span>(<span class="dt">cooling =</span> <span class="kw">c</span>(<span class="st">&#39;gcc&#39;</span>,<span class="st">&#39;ecc&#39;</span>,<span class="st">&#39;erc&#39;</span>,<span class="st">&#39;hpc&#39;</span>), </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true"></a>             <span class="dt">other =</span> <span class="kw">c</span>(<span class="st">&#39;gc&#39;</span>, <span class="st">&#39;ec&#39;</span>, <span class="st">&#39;er&#39;</span>)), <span class="dt">un.nest.el =</span> <span class="ot">TRUE</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true"></a><span class="kw">summary</span>(nl)</span></code></pre></div>
<pre><code>## 
## Call:
## mlogit(formula = depvar ~ ich + och + icca + occa + inc.room + 
##     inc.cooling + int.cooling | 0, data = HC, nests = list(cooling = c(&quot;gcc&quot;, 
##     &quot;ecc&quot;, &quot;erc&quot;, &quot;hpc&quot;), other = c(&quot;gc&quot;, &quot;ec&quot;, &quot;er&quot;)), un.nest.el = TRUE)
## 
## Frequencies of alternatives:choice
##    ec   ecc    er   erc    gc   gcc   hpc 
## 0.004 0.016 0.032 0.004 0.096 0.744 0.104 
## 
## bfgs method
## 11 iterations, 0h:0m:0s 
## g&#39;(-H)^-1g = 7.26E-06 
## successive function values within tolerance limits 
## 
## Coefficients :
##              Estimate Std. Error z-value  Pr(&gt;|z|)    
## ich         -0.554878   0.144205 -3.8478 0.0001192 ***
## och         -0.857886   0.255313 -3.3601 0.0007791 ***
## icca        -0.225079   0.144423 -1.5585 0.1191212    
## occa        -1.089458   1.219821 -0.8931 0.3717882    
## inc.room    -0.378971   0.099631 -3.8038 0.0001425 ***
## inc.cooling  0.249575   0.059213  4.2149 2.499e-05 ***
## int.cooling -6.000415   5.562423 -1.0787 0.2807030    
## iv           0.585922   0.179708  3.2604 0.0011125 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Log-Likelihood: -178.12</code></pre>
<ol style="list-style-type: lower-alpha">
<li>The estimated log-sum coefficient is <span class="math inline">\(0.59\)</span>. What does this estimate tell you about the degree of correlation in unobserved factors over alternatives within each nest?</li>
</ol>
<blockquote>
<p>The correlation is approximately <span class="math inline">\(1-0.59=0.41\)</span>. It’s a moderate correlation.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Test the hypothesis that the log-sum coefficient is 1.0 (the value that it takes for a standard logit model.) Can the hypothesis that the true model is standard logit be rejected?</li>
</ol>
<blockquote>
<p>We can use a t-test of the hypothesis that the log-sum coefficient equal to 1. The t-statistic is :</p>
</blockquote>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true"></a> (<span class="kw">coef</span>(nl)[<span class="st">&#39;iv&#39;</span>] <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">vcov</span>(nl)[<span class="st">&#39;iv&#39;</span>, <span class="st">&#39;iv&#39;</span>])</span></code></pre></div>
<pre><code>##        iv 
## -2.304171</code></pre>
<blockquote>
<p>The critical value of t for 95% confidence is 1.96. So we can reject the hypothesis at 95% confidence.</p>
</blockquote>
<blockquote>
<p>We can also use a likelihood ratio test because the multinomial logit is a special case of the nested model.</p>
</blockquote>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true"></a><span class="co"># First estimate the multinomial logit model</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true"></a>ml &lt;-<span class="st"> </span><span class="kw">update</span>(nl, <span class="dt">nests =</span> <span class="ot">NULL</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true"></a><span class="kw">lrtest</span>(nl, ml)</span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: depvar ~ ich + och + icca + occa + inc.room + inc.cooling + int.cooling | 
##     0
## Model 2: depvar ~ ich + och + icca + occa + inc.room + inc.cooling + int.cooling | 
##     0
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)  
## 1   8 -178.12                       
## 2   7 -180.29 -1 4.3234    0.03759 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<blockquote>
<p>Note that the hypothesis is rejected at 95% confidence, but not at 99% confidence.</p>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Re-estimate the model with the room alternatives in one nest and the central alternatives in another nest. (Note that a heat pump is a central system.)</li>
</ol>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true"></a>nl2 &lt;-<span class="st"> </span><span class="kw">update</span>(nl, <span class="dt">nests =</span> <span class="kw">list</span>(<span class="dt">central =</span> <span class="kw">c</span>(<span class="st">&#39;ec&#39;</span>, <span class="st">&#39;ecc&#39;</span>, <span class="st">&#39;gc&#39;</span>, <span class="st">&#39;gcc&#39;</span>, <span class="st">&#39;hpc&#39;</span>), </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true"></a>                    <span class="dt">room =</span> <span class="kw">c</span>(<span class="st">&#39;er&#39;</span>, <span class="st">&#39;erc&#39;</span>)))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true"></a><span class="kw">summary</span>(nl2)</span></code></pre></div>
<pre><code>## 
## Call:
## mlogit(formula = depvar ~ ich + och + icca + occa + inc.room + 
##     inc.cooling + int.cooling | 0, data = HC, nests = list(central = c(&quot;ec&quot;, 
##     &quot;ecc&quot;, &quot;gc&quot;, &quot;gcc&quot;, &quot;hpc&quot;), room = c(&quot;er&quot;, &quot;erc&quot;)), un.nest.el = TRUE)
## 
## Frequencies of alternatives:choice
##    ec   ecc    er   erc    gc   gcc   hpc 
## 0.004 0.016 0.032 0.004 0.096 0.744 0.104 
## 
## bfgs method
## 10 iterations, 0h:0m:0s 
## g&#39;(-H)^-1g = 5.87E-07 
## gradient close to zero 
## 
## Coefficients :
##              Estimate Std. Error z-value Pr(&gt;|z|)  
## ich          -1.13818    0.54216 -2.0993  0.03579 *
## och          -1.82532    0.93228 -1.9579  0.05024 .
## icca         -0.33746    0.26934 -1.2529  0.21024  
## occa         -2.06328    1.89726 -1.0875  0.27681  
## inc.room     -0.75722    0.34292 -2.2081  0.02723 *
## inc.cooling   0.41689    0.20742  2.0099  0.04444 *
## int.cooling -13.82487    7.94031 -1.7411  0.08167 .
## iv            1.36201    0.65393  2.0828  0.03727 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Log-Likelihood: -180.02</code></pre>
<ol style="list-style-type: lower-alpha">
<li>What does the estimate imply about the substitution patterns across alternatives? Do you think the estimate is plausible?</li>
</ol>
<blockquote>
<p>The log-sum coefficient is over 1. This implies that there is more substitution across nests than within nests. I don’t think this is very reasonable, but people can differ on their concepts of what’s reasonable.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Is the log-sum coefficient significantly different from 1?</li>
</ol>
<p>\begin{answer}[5] The t-statistic is :</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true"></a> (<span class="kw">coef</span>(nl2)[<span class="st">&#39;iv&#39;</span>] <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">vcov</span>(nl2)[<span class="st">&#39;iv&#39;</span>, <span class="st">&#39;iv&#39;</span>])</span></code></pre></div>
<pre><code>##        iv 
## 0.5535849</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true"></a><span class="kw">lrtest</span>(nl2, ml)</span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: depvar ~ ich + och + icca + occa + inc.room + inc.cooling + int.cooling | 
##     0
## Model 2: depvar ~ ich + och + icca + occa + inc.room + inc.cooling + int.cooling | 
##     0
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)
## 1   8 -180.02                     
## 2   7 -180.29 -1 0.5268      0.468</code></pre>
<blockquote>
<p>We cannot reject the hypothesis at standard confidence levels.</p>
</blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>How does the value of the log-likelihood function compare for this model relative to the model in exercise 1, where the cooling alternatives are in one nest and the heating alternatives in the other nest.</li>
</ol>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true"></a><span class="kw">logLik</span>(nl)</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -178.1247 (df=8)</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true"></a><span class="kw">logLik</span>(nl2)</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -180.0231 (df=8)</code></pre>
<blockquote>
<p>The <span class="math inline">\(\ln L\)</span> is worse (more negative.) All in all, this seems like a less appropriate nesting structure.</p>
</blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Rerun the model that has the cooling alternatives in one nest and the non-cooling alternatives in the other nest (like for exercise 1), with a separate log-sum coefficient for each nest.</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true"></a>nl3 &lt;-<span class="st"> </span><span class="kw">update</span>(nl, <span class="dt">un.nest.el =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li>Which nest is estimated to have the higher correlation in unobserved factors? Can you think of a real-world reason for this nest to have a higher correlation?</li>
</ol>
<blockquote>
<p>The correlation in the cooling nest is around 1-0.60 = 0.4 and that for the non-cooling nest is around 1-0.45 = 0.55. So the correlation is higher in the non-cooling nest. Perhaps more variation in comfort when there is no cooling. This variation in comfort is the same for all the non-cooling alternatives.</p>
</blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Are the two log-sum coefficients significantly different from each other? That is, can you reject the hypothesis that the model in exercise 1 is the true model?</li>
</ol>
<blockquote>
<p>We can use a likelihood ratio tests with models <code>nl</code> and <code>nl3</code>.</p>
</blockquote>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true"></a><span class="kw">lrtest</span>(nl, nl3)</span></code></pre></div>
<pre><code>## Likelihood ratio test
## 
## Model 1: depvar ~ ich + och + icca + occa + inc.room + inc.cooling + int.cooling | 
##     0
## Model 2: depvar ~ ich + och + icca + occa + inc.room + inc.cooling + int.cooling | 
##     0
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)
## 1   8 -178.12                     
## 2   9 -178.04  1 0.1758      0.675</code></pre>
<blockquote>
<p>The restricted model is the one from exercise 1 that has one log-sum coefficient. The unrestricted model is the one we just estimated. The test statistics is 0.6299. The critical value of chi-squared with 1 degree of freedom is 3.8 at the 95% confidence level. We therefore cannot reject the hypothesis that the two nests have the same log-sum coefficient.</p>
</blockquote>
<ol start="4" style="list-style-type: decimal">
<li>Rewrite the code to allow three nests. For simplicity, estimate only one log-sum coefficient which is applied to all three nests. Estimate a model with alternatives <code>gcc</code>, <code>ecc</code> and <code>erc</code> in a nest, <code>hpc</code> in a nest alone, and alternatives <code>gc</code>, <code>ec</code> and <code>er</code> in a nest. Does this model seem better or worse than the model in exercise 1, which puts alternative <code>hpc</code> in the same nest as alternatives <code>gcc</code>, <code>ecc</code> and <code>erc</code>?</li>
</ol>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true"></a>nl4 &lt;-<span class="st"> </span><span class="kw">update</span>(nl, <span class="dt">nests=</span><span class="kw">list</span>(<span class="dt">n1 =</span> <span class="kw">c</span>(<span class="st">&#39;gcc&#39;</span>, <span class="st">&#39;ecc&#39;</span>, <span class="st">&#39;erc&#39;</span>), <span class="dt">n2 =</span> <span class="kw">c</span>(<span class="st">&#39;hpc&#39;</span>),</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true"></a>                    <span class="dt">n3 =</span> <span class="kw">c</span>(<span class="st">&#39;gc&#39;</span>, <span class="st">&#39;ec&#39;</span>, <span class="st">&#39;er&#39;</span>)))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true"></a><span class="kw">summary</span>(nl4)</span></code></pre></div>
<pre><code>## 
## Call:
## mlogit(formula = depvar ~ ich + och + icca + occa + inc.room + 
##     inc.cooling + int.cooling | 0, data = HC, nests = list(n1 = c(&quot;gcc&quot;, 
##     &quot;ecc&quot;, &quot;erc&quot;), n2 = c(&quot;hpc&quot;), n3 = c(&quot;gc&quot;, &quot;ec&quot;, &quot;er&quot;)), 
##     un.nest.el = TRUE)
## 
## Frequencies of alternatives:choice
##    ec   ecc    er   erc    gc   gcc   hpc 
## 0.004 0.016 0.032 0.004 0.096 0.744 0.104 
## 
## bfgs method
## 8 iterations, 0h:0m:0s 
## g&#39;(-H)^-1g = 3.71E-08 
## gradient close to zero 
## 
## Coefficients :
##               Estimate Std. Error z-value  Pr(&gt;|z|)    
## ich          -0.838394   0.100546 -8.3384 &lt; 2.2e-16 ***
## och          -1.331598   0.252069 -5.2827 1.273e-07 ***
## icca         -0.256131   0.145564 -1.7596   0.07848 .  
## occa         -1.405656   1.207281 -1.1643   0.24430    
## inc.room     -0.571352   0.077950 -7.3297 2.307e-13 ***
## inc.cooling   0.311355   0.056357  5.5247 3.301e-08 ***
## int.cooling -10.413384   5.612445 -1.8554   0.06354 .  
## iv            0.956544   0.180722  5.2929 1.204e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Log-Likelihood: -180.26</code></pre>
<blockquote>
<p>The <span class="math inline">\(\ln L\)</span> for this model is <span class="math inline">\(-180.26\)</span>, which is lower (more negative) than for the model with two nests, which got <span class="math inline">\(-178.12\)</span>.</p>
</blockquote>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
